# Site settings
author: Deanna
title: New beginnings
header-img: img/home-bg.png
email: dcho0606@gmail.com
copyright_name: Deanna
description: > # this means to ignore newlines until "baseurl:"
  Small steps
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dcho0606

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
